### ISSUE TITLE
Sample on using QuadView with apps rendering to a SurfaceView?

### ISSUE THREAD

**Issue by SephirothFFKH** [LeiaInc/MediaSdkSamples#8]
Is there any documentation or sample on how to implement Leia's QuadView library on apps that are already written to use SurfaceView instead of TextureView / SurfaceTexture?

**Comment by ndahlquist** [comment]
Interesting question. How is your app currently using the SurfaceView? (Do you have it hooked up to a video source like ExoPlayer, or something else?)

**Comment by SephirothFFKH** [comment]
Thank you for your prompt response. I am looking at implementing Lume Pad support to a open source desktop streamer https://github.com/moonlight-stream/moonlight-android From what I see the Surface is set by android.media.MediaCodec

**Comment by ndahlquist** [comment]
If I'm understanding your goal correctly, you want to connect the `MediaCodec` in that project to a `QuadView`.

In that code, they pass a `Surface` to their `MediaCodec` here: https://github.com/moonlight-stream/moonlight-android/blob/3100196939b0a7b6b834b2eabd89be850ad7ef88/app/src/main/java/com/limelight/binding/video/MediaCodecDecoderRenderer.java#L354.

You will want to pass a `Surface` from `QuadView` instead. You can see an example of getting a `Surface` from a `QuadView` here: https://github.com/LeiaInc/MediaSdkSamples/blob/master/sample-play-video/src/main/java/com/leiainc/androidsdk/sample/sample_play_video/VideoActivity.kt#L35. (Note: a `SurfaceTexture` can be converted to a `Surface` by simply calling `Surface(surfaceTexture)`).

Does that help?

**Comment by ndahlquist** [comment]
Said in another way, the repo you linked does: `MediaCodec` -> `Surface` -> `SurfaceView`.

The sample [here](https://github.com/LeiaInc/MediaSdkSamples/blob/master/sample-play-video/src/main/java/com/leiainc/androidsdk/sample/sample_play_video/VideoActivity.kt#L35) does: `ExoPlayer` -> `Surface` -> `QuadView`.

So you would want to combine them: `MediaCodec` -> `Surface` -> `QuadView`.

**Comment by SephirothFFKH** [comment]
Thank you for these details. Yes, this is what I am currently doing but to make this solution work, I am currently modifying the Game class: https://github.com/moonlight-stream/moonlight-android/blob/3100196939b0a7b6b834b2eabd89be850ad7ef88/app/src/main/java/com/limelight/Game.java and the StreamView class https://github.com/moonlight-stream/moonlight-android/blob/3100196939b0a7b6b834b2eabd89be850ad7ef88/app/src/main/java/com/limelight/ui/StreamView.java to render to a TextureView as these classes are required to get touch input and are currently written to interface with a SurfaceView. I wanted to make sure the QuadView library had no SurfaceView hooks before changing all of that.

**Comment by ndahlquist** [comment]
Understood. QuadView has no SurfaceView hooks (internally, it's actually backed by a TextureView).

Feel free to reach out if we can be of any help on your integration; it sounds interesting!
